### ISSUE TITLE
reordering task "Add .my.cnf" in mysql_secure_installation.yml because of missing credentials.

### ISSUE THREAD

**Issue by hferinga** [PCextreme/ansible-role-mariadb#11]
I reordered one of the tasks in in mysql_secure_installation.yml because an error occurred because of missing credentials in tasks before the my.cnf was written while trying to access the database. 
Settting the task Add .my.ncf first in the list solved it for me.

BTW: OS is CentOS 7

**Comment by radriaanse** [comment]
Thanks.
I'll merge this, but after that we are going to archive the project since we aren't using Ansible anymore.
