### ISSUE TITLE
Ansible Galaxy role does not reflect github source

### ISSUE THREAD

**Issue by jcoetsie** [PCextreme/ansible-role-mariadb#3]
I just installed this role through galaxy:

ansible-galaxy install pcextreme.mariadb

But when I look at the dowloaded source, it misses pieces of code 

e.g. in the tasks/main.yml

```
- include: mysql_secure_installation.yml
  when: mysql_secure_installation and mysql_root_password is defined
```

Also the github url: `Ansible Role: MariaDB https://galaxy.ansible.com/list#/roles/2444` is not correct

Can this be fixed?

**Comment by vdvm** [comment]
I don't miss pieces of code. If you want to use the experimental unattended mysql_secure_installation you will have to use --extra-vars as described in README.md.
I have updated the website url in the description.
