### ISSUE TITLE
Role on galaxy missing files.

### ISSUE THREAD

**Issue by erikfrerejean** [PCextreme/ansible-role-mariadb#4]
This is basically the same issue as reported in #3, although that one is closed therefore a new one.

@vdvm something really is ascrew when downloading this role through galaxy. I've been pulling my hair out because I couldn't find the reason the root user wouldn't get a password, even when explicitly setting them through `--extra-vars`.

To be certain that the vars where actually passed correctly into the role I wanted to add some debug statements into the role files, but it turns out that the `mysql_secure_installation.yml` is actually missing when downloading from galaxy _(see attached screenshot)_. I've triggered a new download to assure I had the latest version.

Looking at the timestamps of the files, it is clear what is happening. The `main.yml` file reports that is created on Dec 22, 2014, and `mysql_secure_installation.yml` was added on [Jan 30, 2015](https://github.com/PCextreme/ansible-role-mariadb/commit/3e6822bbcdf4a112b6e9f64aa079b707cbb3693f#diff-2). Could you update the galaxy release to the latest version?

![tasks](https://cloud.githubusercontent.com/assets/197732/13988894/55064f96-f10e-11e5-8b52-4a0c666469a3.png)

![tasks](https://cloud.githubusercontent.com/assets/197732/13988962/9a8c2054-f10e-11e5-9e30-cbd098a05bea.png)

**Comment by vdvm** [comment]
Created a new release and synced with galaxy. Does this fix the issue?

**Comment by erikfrerejean** [comment]
When I run the update then the new files do show up. However my configuration is currently broken so can't test the deployment. I'll test that tomorrow.

**Comment by erikfrerejean** [comment]
@vdvm that seems to work, I however did find an other small bug that prevented the secure installation to finish. See #5.

**Comment by vdvm** [comment]
@erikfrerejean thanks for your help!
