### ISSUE TITLE
LICENSE file is missing

### ISSUE THREAD

**Issue by mtlynch** [PCextreme/ansible-role-mariadb#8]
Thanks for creating this role!

I notice that this repo is marked as licensed under MIT / BSD license, but doesn't contain the actual license notice. Can you include the license in a file called `LICENSE` at the root of the repo to make this clear?

The MIT license can be found here:

http://choosealicense.com/licenses/mit/

Some contributors (including me) would like to contribute, but have employment agreements that prohibit them from contributing to improperly licensed projects.

**Comment by kevindierkx** [comment]
Thank you, the LICENSE file has been added to the repository. dc4cd01ac9d7a3f2a10285f2c1d97a5e988847cf
